### PR TITLE
Add team and burn wallets for Moon Juice

### PR DESCRIPTION
**Pull request by moonjuicealgo**

### CODE REVIEW

**Comment by grzracz** [comment]
JSON is invalid, check with https://jsonlint.com/

**Comment by grzracz** [comment]
Also please remove BNFIRE address from this list since this is a global address and not project-specific, it will be supported for every coin eventually

**Comment by moonjuicealgo** [comment]
Thank you for the help, I have removed the BNFIRE address.

**Review by grzracz — APPROVED** [review]
LGTM

**Pull request merged**
